// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euzucwpvrvzzmpetunip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1enVjd3B2cnZ6em1wZXR1bmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTk4NDAsImV4cCI6MjA1OTY3NTg0MH0.Rvhj5vhppRkZUUAkocLYgY-964YRiUA1jFZO_fu4YRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);